// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFp8KXSnPGs69X6QJCez-aj0Za4_nd_KQ',
    appId: '1:831914266206:web:fb0aa3019d6a771eceeecf',
    messagingSenderId: '831914266206',
    projectId: 'my-church-app-96577',
    authDomain: 'my-church-app-96577.firebaseapp.com',
    storageBucket: 'my-church-app-96577.firebasestorage.app',
    measurementId: 'G-S1YVQ0GRXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VBbjAbnuugHbmkJYOlOOGtCXDQdSh3Q',
    appId: '1:831914266206:android:921d02850f96b507ceeecf',
    messagingSenderId: '831914266206',
    projectId: 'my-church-app-96577',
    storageBucket: 'my-church-app-96577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZj8ch6DKe1XCIQkjRwxCTedt0DzKl-I0',
    appId: '1:831914266206:ios:8ed0cf98789548e2ceeecf',
    messagingSenderId: '831914266206',
    projectId: 'my-church-app-96577',
    storageBucket: 'my-church-app-96577.firebasestorage.app',
    iosBundleId: 'com.example.myChurchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZj8ch6DKe1XCIQkjRwxCTedt0DzKl-I0',
    appId: '1:831914266206:ios:8ed0cf98789548e2ceeecf',
    messagingSenderId: '831914266206',
    projectId: 'my-church-app-96577',
    storageBucket: 'my-church-app-96577.firebasestorage.app',
    iosBundleId: 'com.example.myChurchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFp8KXSnPGs69X6QJCez-aj0Za4_nd_KQ',
    appId: '1:831914266206:web:a333fbc3b6775743ceeecf',
    messagingSenderId: '831914266206',
    projectId: 'my-church-app-96577',
    authDomain: 'my-church-app-96577.firebaseapp.com',
    storageBucket: 'my-church-app-96577.firebasestorage.app',
    measurementId: 'G-QYHQ7R3282',
  );

}